### ISSUE TITLE
磁力无法下载

### ISSUE THREAD

**Issue by s0ng1** [NihaoKangkang/Chinese-Common-Password-List#1]
RT

**Comment by NihaoKangkang** [comment]
我现在实测迅雷可以下载
<img width="646" alt="WechatIMG20" src="https://github.com/user-attachments/assets/2cc08530-4f2d-4c4a-aaf6-be20d26b9430" />

**Comment by xzajyjs** [comment]
确实无法下载，qb 迅雷都试了

**Comment by NihaoKangkang** [comment]
> 确实无法下载，qb 迅雷都试了

迅雷开全局代理可以下载，如果短时间没速度，等半小时。或者自行从谷歌上查找网易泄漏数据库torrent，类似问题今后不做回复。
